name: First Workflow
on: workflow_dispatch
jobs:
    first-job:
        runs-on: windows-latest
        steps:
            - name: print sample
              run: |
                  echo "Hello!"
                  echo "Bye!"
